"""Alembic migration を空の使い捨て PostgreSQL で検証する。"""

from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from uuid import uuid4

import psycopg
import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util import AutogenerateDiffsDetected
from psycopg.conninfo import conninfo_to_dict
from psycopg.types.json import Jsonb
from sqlalchemy import Column, Integer, MetaData, Table
from sqlalchemy.engine import URL

from pitchlog.db.base import Base
from pitchlog.db.engine import create_database_engine

from .conftest import DisposablePostgres

pytestmark = pytest.mark.requires_db

_BACKEND_ROOT = Path(__file__).resolve().parents[2]
_REVISION = "0003_games_lineups_participation"
_TRIGGER_NAME = "trg_team_records_kind_immutable"
_TRIGGER_DEFINITION = (
    "CREATE TRIGGER trg_team_records_kind_immutable BEFORE UPDATE OF kind "
    "ON team_records FOR EACH ROW EXECUTE FUNCTION "
    "prevent_team_records_kind_update()"
)
_FUNCTION_DEFINITION = """
CREATE OR REPLACE FUNCTION public.prevent_team_records_kind_update()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.kind IS DISTINCT FROM OLD.kind THEN
        RAISE EXCEPTION 'team_records.kind is immutable'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$
"""
_GAME_LINEUP_TRIGGER_NAME = "trg_game_lineups_entries_immutable"
_GAME_LINEUP_TRIGGER_DEFINITION = (
    "CREATE TRIGGER trg_game_lineups_entries_immutable BEFORE UPDATE OF "
    "entries_with_uniform_number_snapshot ON game_lineups FOR EACH ROW "
    "EXECUTE FUNCTION prevent_game_lineups_entries_update()"
)
_GAME_LINEUP_FUNCTION_DEFINITION = """
CREATE OR REPLACE FUNCTION public.prevent_game_lineups_entries_update()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.entries_with_uniform_number_snapshot IS DISTINCT FROM
       OLD.entries_with_uniform_number_snapshot THEN
        RAISE EXCEPTION 'game_lineups.entries_with_uniform_number_snapshot is immutable'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$function$
"""


def _alembic_config() -> Config:
    """Backend 配下の Alembic 設定を返す。

    Returns:
        migration コマンドに渡す設定。
    """
    return Config(str(_BACKEND_ROOT / "alembic.ini"))


def _sqlalchemy_url(dsn: str) -> str:
    """使い捨てクラスタの conninfo から裸の PostgreSQL URL を作る。

    Args:
        dsn: 既存 factory が返す libpq conninfo。

    Returns:
        同じ接続先を指す裸の PostgreSQL URL。
    """
    parameters = conninfo_to_dict(dsn)
    required = {key: parameters.get(key) for key in ("host", "port", "dbname", "user")}
    if any(value is None for value in required.values()):
        raise AssertionError("使い捨てクラスタ DSN に接続先情報が不足している")

    password = parameters.get("password")
    return URL.create(
        "postgresql",
        username=str(required["user"]),
        password=None if password is None else str(password),
        host=str(required["host"]),
        port=int(str(required["port"])),
        database=str(required["dbname"]),
    ).render_as_string(hide_password=False)


def test_schema_revision_and_application_engine_use_the_database(
    disposable_postgres_cluster: Callable[
        [], AbstractContextManager[DisposablePostgres]
    ],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """空 DB で upgrade・head 検査・差分検査・実接続を完走する。"""
    with disposable_postgres_cluster() as cluster:
        database_url = _sqlalchemy_url(cluster.admin_dsn)
        monkeypatch.setenv("PITCHLOG_MIGRATION_DATABASE_URL", database_url)
        monkeypatch.setenv("PITCHLOG_DATABASE_URL", database_url)
        monkeypatch.setenv("PITCHLOG_DATABASE_POOLED", "false")
        config = _alembic_config()

        heads = ScriptDirectory.from_config(config).get_heads()
        assert heads == [_REVISION]

        command.upgrade(config, "head")
        command.current(config, check_heads=True)
        command.check(config)

        engine = create_database_engine()
        try:
            assert engine.dialect.driver == "psycopg"
            with engine.connect() as connection:
                assert connection.exec_driver_sql("SELECT 1").scalar_one() == 1
        finally:
            engine.dispose()


def test_alembic_check_is_red_for_test_only_metadata_difference(
    disposable_postgres_cluster: Callable[
        [], AbstractContextManager[DisposablePostgres]
    ],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """test-only metadata の未 migration 表を Alembic が拒否すると示す。"""
    with disposable_postgres_cluster() as cluster:
        monkeypatch.setenv(
            "PITCHLOG_MIGRATION_DATABASE_URL",
            _sqlalchemy_url(cluster.admin_dsn),
        )
        config = _alembic_config()
        command.upgrade(config, "head")

        test_metadata = MetaData()
        Table(
            "test_only_metadata_probe",
            test_metadata,
            Column("id", Integer, primary_key=True),
        )
        monkeypatch.setattr(Base, "metadata", test_metadata)

        with pytest.raises(
            AutogenerateDiffsDetected,
            match="test_only_metadata_probe",
        ):
            command.check(config)


def _normalize_sql(definition: str) -> str:
    """カタログが返す SQL 全文の空白だけを比較用に正規化する。"""
    return " ".join(definition.split())


def _trigger_catalog_contract(
    connection: psycopg.Connection[Any],
) -> tuple[str, str, list[str], str, str]:
    """Kind 不変性トリガの構造と関数定義をカタログから取得する。"""
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                pg_get_triggerdef(trigger_row.oid, true),
                relation.relname,
                ARRAY(
                    SELECT attribute.attname
                    FROM unnest(trigger_row.tgattr::smallint[])
                        WITH ORDINALITY AS target(attnum, position)
                    JOIN pg_attribute AS attribute
                      ON attribute.attrelid = trigger_row.tgrelid
                     AND attribute.attnum = target.attnum
                    ORDER BY target.position
                ),
                trigger_row.tgenabled,
                pg_get_functiondef(function_row.oid)
            FROM pg_trigger AS trigger_row
            JOIN pg_class AS relation ON relation.oid = trigger_row.tgrelid
            JOIN pg_proc AS function_row
              ON function_row.oid = trigger_row.tgfoid
            WHERE trigger_row.tgname = %s
              AND NOT trigger_row.tgisinternal
            """,
            (_TRIGGER_NAME,),
        )
        row = cursor.fetchone()
    if row is None:
        raise AssertionError("team_records.kind の不変性トリガが存在しない")
    return str(row[0]), str(row[1]), list(row[2]), str(row[3]), str(row[4])


def _assert_trigger_and_function_are_absent(
    connection: psycopg.Connection[Any],
) -> None:
    """Downgrade 後にトリガと関数が残っていないことを検査する。"""
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                EXISTS (
                    SELECT 1 FROM pg_trigger
                    WHERE tgname = %s AND NOT tgisinternal
                ),
                to_regprocedure('public.prevent_team_records_kind_update()')
            """,
            (_TRIGGER_NAME,),
        )
        row = cursor.fetchone()
    assert row == (False, None)


def test_team_kind_trigger_and_migration_round_trip(
    disposable_postgres_cluster: Callable[
        [], AbstractContextManager[DisposablePostgres]
    ],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Kind の不変性と migration の downgrade・再 upgrade を検査する。"""
    with disposable_postgres_cluster() as cluster:
        monkeypatch.setenv(
            "PITCHLOG_MIGRATION_DATABASE_URL",
            _sqlalchemy_url(cluster.admin_dsn),
        )
        config = _alembic_config()
        command.upgrade(config, "head")

        with psycopg.connect(cluster.admin_dsn, autocommit=True) as connection:
            trigger, table, columns, enabled, function = _trigger_catalog_contract(
                connection
            )
            assert _normalize_sql(trigger) == _normalize_sql(_TRIGGER_DEFINITION)
            assert table == "team_records"
            assert columns == ["kind"]
            assert enabled == "O"
            assert _normalize_sql(function) == _normalize_sql(_FUNCTION_DEFINITION)

            tenant_id = uuid4()
            self_team_id = uuid4()
            opponent_team_id = uuid4()
            with connection.cursor() as cursor:
                cursor.execute(
                    "INSERT INTO tenants (id, name) VALUES (%s, %s)",
                    (tenant_id, "テストテナント"),
                )
                cursor.executemany(
                    """
                    INSERT INTO team_records (tenant_id, id, kind, name)
                    VALUES (%s, %s, %s, %s)
                    """,
                    [
                        (tenant_id, self_team_id, "self", "自チーム"),
                        (tenant_id, opponent_team_id, "opponent", "対戦相手"),
                    ],
                )
                with pytest.raises(
                    psycopg.errors.CheckViolation,
                    match="team_records.kind is immutable",
                ):
                    cursor.execute(
                        """
                        UPDATE team_records SET kind = 'self'
                        WHERE tenant_id = %s AND id = %s
                        """,
                        (tenant_id, opponent_team_id),
                    )
                cursor.execute(
                    """
                    UPDATE team_records SET name = '更新後'
                    WHERE tenant_id = %s AND id = %s
                    RETURNING name
                    """,
                    (tenant_id, self_team_id),
                )
                assert cursor.fetchone() == ("更新後",)
                cursor.execute(
                    """
                    UPDATE team_records SET hidden_at = CURRENT_TIMESTAMP
                    WHERE tenant_id = %s AND id = %s
                    RETURNING hidden_at IS NOT NULL
                    """,
                    (tenant_id, opponent_team_id),
                )
                assert cursor.fetchone() == (True,)

        command.downgrade(config, "0001_initialize_schema")
        with psycopg.connect(cluster.admin_dsn, autocommit=True) as connection:
            _assert_trigger_and_function_are_absent(connection)

        command.upgrade(config, "head")
        command.current(config, check_heads=True)
        command.check(config)


def _game_lineup_trigger_catalog_contract(
    connection: psycopg.Connection[Any],
) -> tuple[str, str, list[str], str, str]:
    """先発背番号スナップショットのトリガ構造と関数定義を取得する。"""
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                pg_get_triggerdef(trigger_row.oid, true),
                relation.relname,
                ARRAY(
                    SELECT attribute.attname
                    FROM unnest(trigger_row.tgattr::smallint[])
                        WITH ORDINALITY AS target(attnum, position)
                    JOIN pg_attribute AS attribute
                      ON attribute.attrelid = trigger_row.tgrelid
                     AND attribute.attnum = target.attnum
                    ORDER BY target.position
                ),
                trigger_row.tgenabled,
                pg_get_functiondef(function_row.oid)
            FROM pg_trigger AS trigger_row
            JOIN pg_class AS relation ON relation.oid = trigger_row.tgrelid
            JOIN pg_proc AS function_row
              ON function_row.oid = trigger_row.tgfoid
            WHERE trigger_row.tgname = %s
              AND NOT trigger_row.tgisinternal
            """,
            (_GAME_LINEUP_TRIGGER_NAME,),
        )
        row = cursor.fetchone()
    if row is None:
        raise AssertionError("試合スタメンの背番号スナップショットトリガが存在しない")
    return str(row[0]), str(row[1]), list(row[2]), str(row[3]), str(row[4])


def _index_catalog_contract(
    connection: psycopg.Connection[Any], index_name: str
) -> tuple[str, str, list[str], str | None, bool]:
    """索引定義・対象表・列順・述語・一意性をカタログから取得する。"""
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                pg_get_indexdef(index_row.indexrelid, 0, true),
                table_relation.relname,
                ARRAY(
                    SELECT pg_get_indexdef(
                        index_row.indexrelid,
                        position,
                        true
                    )
                    FROM generate_series(
                        1,
                        index_row.indnkeyatts
                    ) AS position
                    ORDER BY position
                ),
                pg_get_expr(index_row.indpred, index_row.indrelid, true),
                index_row.indisunique
            FROM pg_index AS index_row
            JOIN pg_class AS index_relation
              ON index_relation.oid = index_row.indexrelid
            JOIN pg_class AS table_relation
              ON table_relation.oid = index_row.indrelid
            WHERE index_relation.relname = %s
            """,
            (index_name,),
        )
        row = cursor.fetchone()
    if row is None:
        raise AssertionError(f"索引が存在しない: {index_name}")
    predicate = None if row[3] is None else str(row[3])
    return str(row[0]), str(row[1]), list(row[2]), predicate, bool(row[4])


def _assert_step_seven_objects_are_absent(
    connection: psycopg.Connection[Any],
) -> None:
    """Downgrade 後にステップ 7 の表・トリガ・関数が残っていないと示す。"""
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                to_regclass('public.games'),
                to_regclass('public.lineup_memories'),
                to_regclass('public.game_lineups'),
                to_regclass('public.participation_intervals'),
                EXISTS (
                    SELECT 1 FROM pg_trigger
                    WHERE tgname = %s AND NOT tgisinternal
                ),
                to_regprocedure('public.prevent_game_lineups_entries_update()')
            """,
            (_GAME_LINEUP_TRIGGER_NAME,),
        )
        row = cursor.fetchone()
    assert row == (None, None, None, None, False, None)


def test_game_state_constraints_and_migration_round_trip(
    disposable_postgres_cluster: Callable[
        [], AbstractContextManager[DisposablePostgres]
    ],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """試合系4表の索引・必須列・不変性と migration 往復を検査する。"""
    with disposable_postgres_cluster() as cluster:
        monkeypatch.setenv(
            "PITCHLOG_MIGRATION_DATABASE_URL",
            _sqlalchemy_url(cluster.admin_dsn),
        )
        config = _alembic_config()
        command.upgrade(config, "head")

        with psycopg.connect(cluster.admin_dsn, autocommit=True) as connection:
            trigger, table, columns, enabled, function = (
                _game_lineup_trigger_catalog_contract(connection)
            )
            assert _normalize_sql(trigger) == _normalize_sql(
                _GAME_LINEUP_TRIGGER_DEFINITION
            )
            assert table == "game_lineups"
            assert columns == ["entries_with_uniform_number_snapshot"]
            assert enabled == "O"
            assert _normalize_sql(function) == _normalize_sql(
                _GAME_LINEUP_FUNCTION_DEFINITION
            )

            expected_indexes = {
                "uq_lineup_memories_active": (
                    "lineup_memories",
                    ["tenant_id", "team_record_id"],
                ),
                "uq_participation_intervals_active": (
                    "participation_intervals",
                    [
                        "tenant_id",
                        "game_id",
                        "slot_kind",
                        "slot",
                        "valid_from_d2",
                    ],
                ),
            }
            for index_name, (
                expected_table,
                expected_columns,
            ) in expected_indexes.items():
                definition, index_table, index_columns, predicate, unique = (
                    _index_catalog_contract(connection, index_name)
                )
                assert _normalize_sql(definition).startswith(
                    f"CREATE UNIQUE INDEX {index_name} "
                )
                assert index_table == expected_table
                assert index_columns == expected_columns
                assert predicate == "retired_at IS NULL"
                assert unique

            tenant_id = uuid4()
            self_team_id = uuid4()
            opponent_team_id = uuid4()
            game_id = uuid4()
            scheduled_at = datetime(2026, 9, 11, 10, 0, tzinfo=UTC)
            with connection.cursor() as cursor:
                cursor.execute(
                    "INSERT INTO tenants (id, name) VALUES (%s, %s)",
                    (tenant_id, "試合テストテナント"),
                )
                cursor.executemany(
                    """
                    INSERT INTO team_records (tenant_id, id, kind, name)
                    VALUES (%s, %s, %s, %s)
                    """,
                    [
                        (tenant_id, self_team_id, "self", "自チーム"),
                        (tenant_id, opponent_team_id, "opponent", "対戦相手"),
                    ],
                )

                game_values: dict[str, object] = {
                    "tenant_id": tenant_id,
                    "id": game_id,
                    "scheduled_at": scheduled_at,
                    "game_type_key": "official",
                    "tournament_key": "autumn",
                    "away_team_record_id": opponent_team_id,
                    "home_team_record_id": self_team_id,
                    "applied_rules": Jsonb({}),
                }
                insert_game = """
                    INSERT INTO games (
                        tenant_id,
                        id,
                        scheduled_at,
                        game_type_key,
                        tournament_key,
                        away_team_record_id,
                        home_team_record_id,
                        applied_rules
                    ) VALUES (
                        %(tenant_id)s,
                        %(id)s,
                        %(scheduled_at)s,
                        %(game_type_key)s,
                        %(tournament_key)s,
                        %(away_team_record_id)s,
                        %(home_team_record_id)s,
                        %(applied_rules)s
                    )
                """
                for required_column in (
                    "scheduled_at",
                    "game_type_key",
                    "tournament_key",
                ):
                    invalid_values = game_values | {
                        "id": uuid4(),
                        required_column: None,
                    }
                    with pytest.raises(
                        psycopg.errors.NotNullViolation,
                        match=required_column,
                    ):
                        cursor.execute(insert_game, invalid_values)

                cursor.execute(insert_game, game_values)
                lineup_id = uuid4()
                cursor.execute(
                    """
                    INSERT INTO game_lineups (
                        tenant_id,
                        id,
                        game_id,
                        team_record_id,
                        entries_with_uniform_number_snapshot
                    ) VALUES (%s, %s, %s, %s, %s)
                    """,
                    (
                        tenant_id,
                        lineup_id,
                        game_id,
                        self_team_id,
                        Jsonb([{"slot": "1", "uniform_number_snapshot": "10"}]),
                    ),
                )
                with pytest.raises(
                    psycopg.errors.CheckViolation,
                    match=(
                        "game_lineups.entries_with_uniform_number_snapshot is immutable"
                    ),
                ):
                    cursor.execute(
                        """
                        UPDATE game_lineups
                        SET entries_with_uniform_number_snapshot = %s
                        WHERE tenant_id = %s AND id = %s
                        """,
                        (
                            Jsonb(
                                [
                                    {
                                        "slot": "1",
                                        "uniform_number_snapshot": "11",
                                    }
                                ]
                            ),
                            tenant_id,
                            lineup_id,
                        ),
                    )

        command.downgrade(config, "0002_tenants_teams_players")
        with psycopg.connect(cluster.admin_dsn, autocommit=True) as connection:
            _assert_step_seven_objects_are_absent(connection)

        command.upgrade(config, "head")
        command.current(config, check_heads=True)
        command.check(config)
