"""Alembic migration を空の使い捨て PostgreSQL で検証する。"""

from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util import AutogenerateDiffsDetected
from psycopg.conninfo import conninfo_to_dict
from sqlalchemy import Column, Integer, MetaData, Table
from sqlalchemy.engine import URL

from pitchlog.db.base import Base
from pitchlog.db.engine import create_database_engine

from .conftest import DisposablePostgres

pytestmark = pytest.mark.requires_db

_BACKEND_ROOT = Path(__file__).resolve().parents[2]
_REVISION = "0001_initialize_schema"


def _alembic_config() -> Config:
    """Backend 配下の Alembic 設定を返す。

    Returns:
        migration コマンドに渡す設定。
    """
    return Config(str(_BACKEND_ROOT / "alembic.ini"))


def _sqlalchemy_url(dsn: str) -> str:
    """使い捨てクラスタの conninfo から裸の PostgreSQL URL を作る。

    Args:
        dsn: 既存 factory が返す libpq conninfo。

    Returns:
        同じ接続先を指す裸の PostgreSQL URL。
    """
    parameters = conninfo_to_dict(dsn)
    required = {key: parameters.get(key) for key in ("host", "port", "dbname", "user")}
    if any(value is None for value in required.values()):
        raise AssertionError("使い捨てクラスタ DSN に接続先情報が不足している")

    password = parameters.get("password")
    return URL.create(
        "postgresql",
        username=str(required["user"]),
        password=None if password is None else str(password),
        host=str(required["host"]),
        port=int(str(required["port"])),
        database=str(required["dbname"]),
    ).render_as_string(hide_password=False)


def test_minimal_revision_and_application_engine_use_the_empty_database(
    disposable_postgres_cluster: Callable[
        [], AbstractContextManager[DisposablePostgres]
    ],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """空 DB で upgrade・head 検査・差分検査・実接続を完走する。"""
    with disposable_postgres_cluster() as cluster:
        database_url = _sqlalchemy_url(cluster.admin_dsn)
        monkeypatch.setenv("PITCHLOG_MIGRATION_DATABASE_URL", database_url)
        monkeypatch.setenv("PITCHLOG_DATABASE_URL", database_url)
        config = _alembic_config()

        heads = ScriptDirectory.from_config(config).get_heads()
        assert heads == [_REVISION]

        command.upgrade(config, "head")
        command.current(config, check_heads=True)
        command.check(config)

        engine = create_database_engine()
        try:
            assert engine.dialect.driver == "psycopg"
            with engine.connect() as connection:
                assert connection.exec_driver_sql("SELECT 1").scalar_one() == 1
        finally:
            engine.dispose()


def test_alembic_check_is_red_for_test_only_metadata_difference(
    disposable_postgres_cluster: Callable[
        [], AbstractContextManager[DisposablePostgres]
    ],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """test-only metadata の未 migration 表を Alembic が拒否すると示す。"""
    with disposable_postgres_cluster() as cluster:
        monkeypatch.setenv(
            "PITCHLOG_MIGRATION_DATABASE_URL",
            _sqlalchemy_url(cluster.admin_dsn),
        )
        config = _alembic_config()
        command.upgrade(config, "head")

        test_metadata = MetaData()
        Table(
            "test_only_metadata_probe",
            test_metadata,
            Column("id", Integer, primary_key=True),
        )
        monkeypatch.setattr(Base, "metadata", test_metadata)

        with pytest.raises(
            AutogenerateDiffsDetected,
            match="test_only_metadata_probe",
        ):
            command.check(config)
